runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /(.+)
    static_files: \1
    upload: (.*)

  - url: /
    static_files: index.html
    upload: index.html

skip_files:
- node_modules/*